
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname:eureka.kyeapi.com}:${eureka.server.port:18761}/eureka/
##    register-with-eureka: false
#  instance:
#    prefer-ip-address: true

server:
  port: 1860
  servlet:
    context-path: /
  compression:
    enabled: true
    
spring:
  application:
    name: toby-flux-demo
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3406/toby_db?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    

logging:
  file: ${spring.application.name}
  level:
    ROOT: info
    org.springframework: info
    org.springframework.web.servlet.view: info
    org.springframework.web.servlet.mvc: info
    io.undertow.request: info
    com.kyexpress: debug
    com.kyexpress.framework.mybatis: debug
    com.github.pagehelper: TRACE
    com.zaxxer.hikari: TRACE
    com.netflix.discovery: WARN
